package com.seven.cow.spring.boot.autoconfigure.constant;

/**
 * @ClassName Field
 * @Description 报文字段key自定义
 * Version 0.0.1
 **/
public final class FieldConstants {
    public final static String ID = "_id";
    public final static Boolean BOOLEAN_TRUE = Boolean.TRUE;
    public final static Boolean BOOLEAN_FALSE = Boolean.FALSE;
    public final static Integer INTEGER_TRUE = 1;
    public final static Integer INTEGER_FALSE = 0;
    public final static String A = "a";
    public final static String B = "b";
    public final static String C = "c";
    public final static String D = "d";
    public final static String E = "e";
    public final static String F = "f";
    public final static String G = "g";
    public final static String H = "h";
    public final static String I = "i";
    public final static String J = "j";
    public final static String K = "k";
    public final static String L = "l";
    public final static String M = "m";
    public final static String N = "n";
    public final static String O = "o";
    public final static String P = "p";
    public final static String Q = "q";
    public final static String R = "r";
    public final static String S = "s";
    public final static String T = "t";
    public final static String U = "u";
    public final static String V = "v";
    public final static String W = "w";
    public final static String X = "x";
    public final static String Y = "y";
    public final static String Z = "z";
    public final static String AA = "aa";
    public final static String AB = "ab";
    public final static String AC = "ac";
    public final static String AD = "ad";
    public final static String AE = "ae";
    public final static String AF = "af";
    public final static String AG = "ag";
    public final static String AH = "ah";
    public final static String AI = "ai";
    public final static String AJ = "aj";
    public final static String AK = "ak";
    public final static String AL = "al";
    public final static String AM = "am";
    public final static String AN = "an";
    public final static String AO = "ao";
    public final static String AP = "ap";
    public final static String AQ = "aq";
    public final static String AR = "ar";
    public final static String AS = "as";
    public final static String AT = "at";
    public final static String AU = "au";
    public final static String AV = "av";
    public final static String AW = "aw";
    public final static String AX = "ax";
    public final static String AY = "ay";
    public final static String AZ = "az";
    public final static String BA = "ba";
    public final static String BB = "bb";
    public final static String BC = "bc";
    public final static String BD = "bd";
    public final static String BE = "be";
    public final static String BF = "bf";
    public final static String BG = "bg";
    public final static String BH = "bh";
    public final static String BI = "bi";
    public final static String BJ = "bj";
    public final static String BK = "bk";
    public final static String BL = "bl";
    public final static String BM = "bm";
    public final static String BN = "bn";
    public final static String BO = "bo";
    public final static String BP = "bp";
    public final static String BQ = "bq";
    public final static String BR = "br";
    public final static String BS = "bs";
    public final static String BT = "bt";
    public final static String BU = "bu";
    public final static String BV = "bv";
    public final static String BW = "bw";
    public final static String BX = "bx";
    public final static String BY = "by";
    public final static String BZ = "bz";
}
